# Site settings
title: "An Eye 4 AI Podcast"
description: "Hosted by Annielytics"
podcast-description: "Welcome to my Women in Tech podcast site.
url:  "https://An-Eye-4-AI-Podcast.netlify.app/" # Actual base url of the website
baseurl: "/episodes"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Laura Edell"
  email: "aneye4ai@gmail.com"
  url: "https://aka.ms/annielytics"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll, AnEye4AI, annielytix, annielytics, AI, LLM]
theme: jekyll-podcaster

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]


#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: Laura_E_Edell
  card: summary
facebook:
  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: Laura Edell
  links:
    - https://github.com/Annielytix
    - https://twitter.com/Laura_E_Edell
    - https://www.linkedin.com/in/lauraerinedell/
lang: en

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: An Eye 4 AI Podcast
podcast_author: Laura Edell
podcast_email: aneye4ai@gmail.com
podcast_subtitle: "Hosted by Annielytix"
podcast_summary: "This is your podcast's summary."
podcast_description: "This is your podcast's description."
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: en
podcast_launch: "2020-04-20" #Launch date of your podcast
podcast_copyright: "&#xA9;An Eye 4 AI LLC"
podcast_feed: "https://anchor.fm/s/37730ff0/podcast/rss"
podcast_artwork: "/assets/img/Podcast_Cover.png"
